---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# # metadata, to generate demo & fontello info dialogs
# meta:
#
#  author: Daniel Buce
#  homepage: http://...
#  email: ...
#  twitter: http://twitter.com/...
#  dribble: http://dribbble.com/...
#  license: SIL
#  license_url: http://scripts.sil.org/OFL
#
#   css-prefix: "icon-"             # prefix for css-generated classes
#   demo-columns: 4                 # used for html demo page generation
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Regular
#
#
# #
# # Optional. You can apply global rescale + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%. 
# #
# transform:
#   baseline: 0.2                 # baseline for rescale symmetry. Default value
#                                 # calculated from ascent/decsent
#   rescale: 0.68                 # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - file: glyph1_file           # file name, without extention
#     from: 0xNNN                 # Source code for remapper or merge tool
#     code: 0xNNN                 # Symbol code 0x - hex
#     css: icon-gpyph1-name       # For generated CSS
#     search: [word1, word2]      # Search aliases (array). CSS name will be
#                                 # included automatically
#     src: first_font_alias       # alias to font for merge tool
#                                 # list of aliases in src_fonts section
#
#     #
#     # local transformations, only for this glyph (optional)
#     #
#     transform:                  # personal glyph transformation.
#       rescale_rel               # *_rel - applyed after global.
#       offset: 0.2               # without *_rel - override global
#
# #
# # Fonts aliases used only in font merge tool
# #
# src_fonts:
#   first_font_alias: "/absolute/path/to/first/font.ttf"

################################################################################
#


meta:
  author: isux
  homepage: http://isux.tencent.com/
  twitter: https://twitter.com/isux/
  license: CC BY-SA 3.0
  license_url: http://creativecommons.org/licenses/by-sa/3.0/

  css_prefix: "icon-"
  columns: 4

#transform:
 # baseline: 0.5
  #rescale: 1.2
  #offset: -0.44

font:
  version: "1.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: sola-aoi

  fullname: sola-aoi
  familyname: sola-aoi

  copyright: (c) isux tencent 2012

  ascent: 850
  descent: 150
  weight: Regular


glyphs:

  -
    css: at
    code: 0xf798
    uid: d97f2667f3da0845da7baaeda485e2da 
    meta:
      author: isux
      email: isux@qq.com
    search: [at]
  -
    css: qq
    code: 0xf799
    uid: 33a46defb9757ff9bb14b0f40a432cc4 
    meta:
      author: isux
      email: isux@qq.com
    search: [qq]
  -
    css: activity
    code: 0xf800
    uid: d522bf9b0fbe1e8c501db1ff871b359f 
    meta:
      author: isux
      email: isux@qq.com
    search: [activity]
  -
    css: app-add
    code: 0xf861
    uid: 3aa86a7bb0229b2a681f39ae7a2441a6 
    meta:
      author: isux
      email: isux@qq.com
    search: [app]
  -
    css: app-center
    code: 0xf862
    uid: f220a344361b32db28c66048168faf9c 
    meta:
      author: isux
      email: isux@qq.com
    search: [app, center]
  - 
    css: app-center2
    code: 0xf826
    uid: ce8a6dc1b032ced1d414c1b61098dfe3 
    meta:
      author: isux
      email: isux@qq.com
    search: [app, center]
  -
    css: arrow-top
    code: 0xf863
    uid: ec94ff56b8332bd3edc3a4e90e7749e7 
    meta:
      author: isux
      email: isux@qq.com
    search: [arrow, top]
  -
    css: board
    code: 0xf864
    uid: ed99f7b52ba602f0ca3c4f0c2e0c5093 
    meta:
      author: isux
      email: isux@qq.com
    search: [board]
  -
    css: cert
    code: 0xf865
    uid: f6474f6853e2276e536c8993268d5fca 
    meta:
      author: isux
      email: isux@qq.com
    search: [cert]
  -
    css: cloudy
    code: 0xf866
    uid: 7ce2e72d9618a8fbf8a48929b7a21129 
    meta:
      author: isux
      email: isux@qq.com
    search: [cloudy, weather]
  -
    css: dress
    code: 0xf867
    uid: b7456e47f7f5b65b43002ca73aa24978 
    meta:
      author: isux
      email: isux@qq.com
    search: [dress]
  -
    css: gift
    code: 0xf868
    uid: d3f8eb91dea871ad107fc0360b9ff171 
    meta:
      author: isux
      email: isux@qq.com
    search: [gift]
  -
    css: homepage
    code: 0xf869
    uid: b7e2aee962ff7c39b5c86eca087af247 
    meta:
      author: isux
      email: isux@qq.com
    search: [homepage]
  -
    css: zan
    code: 0xf871
    uid: 0e74d2ca29545fa136f86b624f14ea0e 
    meta:
      author: isux
      email: isux@qq.com
    search: [zan, like]
  -
    css: zan2
    code: 0xf870
    uid: 9d42e2e7585e0095e9e187e0bec2e2b2 
    meta:
      author: isux
      email: isux@qq.com
    search: [like, zan]
  -
    css: list-more
    code: 0xf872
    uid: e0b38208d9d176a230ed13b9cd67ba03 
    meta:
      author: isux
      email: isux@qq.com
    search: [list, more]
  -
    css: love
    code: 0xf873
    uid: ca067dd82971bf903278a81a3d227f1d 
    meta:
      author: isux
      email: isux@qq.com
    search: [love]
  -
    css: mail
    code: 0xf874
    uid: 12b380d0d2ab84c3247554a38e16cf9e 
    meta:
      author: isux
      email: isux@qq.com
    search: [mail]
  -
    css: myhome
    code: 0xf875
    uid: a136da43c30d3c8e34b5b328dec920e1 
    meta:
      author: isux
      email: isux@qq.com
    search: [myhome, home]
  -
    css: pengyou
    code: 0xf876
    uid: cb6c4d8bde4e9338951335c202118b68 
    meta:
      author: isux
      email: isux@qq.com
    search: [pengyou,logo,tencent]
  -
    css: search
    code: 0xf877
    uid: 55c6cc587abf8016c88193a1b20cdb27 
    meta:
      author: isux
      email: isux@qq.com
    search: [search]
  -
    css: weibo
    code: 0xf878
    uid: 020ae88a09a73581333c657b79d0e4c6 
    meta:
      author: isux
      email: isux@qq.com
    search: [weibo,tencent]
  -
    css: arrow-top2
    code: 0xf879
    uid: 28337250980c696ae6e704026f828081 
    meta:
      author: isux
      email: isux@qq.com
    search: [myhome, home]
  -
    css: arrow-down
    code: 0xf890
    uid: ab90f08ccb5cc45b829a338a45a413a9 
    meta:
      author: isux
      email: isux@qq.com
    search: [pengyou,logo,tencent]
  -
    css: arrow-up
    code: 0xf891
    uid: f6f69e7e826958508a5fafd3dec9b089 
    meta:
      author: isux
      email: isux@qq.com
    search: [search]
  -
    css: arrow-bottom
    code: 0xf892
    uid: a2de4bae385c10f0db8b480f8c1d74a5 
    meta:
      author: isux
      email: isux@qq.com
    search: [weibo,tencent]
